apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: dashkube
  name: dashkube
  namespace: dashkube
  selfLink: /dashkube
spec:
  replicas: 1
  selector:
    app: dashkube
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dashkube
    spec:
      containers:
      - image: bitnami/apache:latest
        name: dashkube
        ports:
        - containerPort: 5555
          protocol: TCP

